(define list (lambda l l))
(define #t (lambda (x y) x))
(define #f (lambda (x y) y))
(define not (lambda (b) (lambda (x y) (b y x))))
(define and (lambda (x y) (x y x)))
(define or (lambda (x y) (x x y)))
